version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_marcas_autos
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marcas_autos_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d marcas_autos_db']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_marcas_autos_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production

      # ðŸ‘‡ AquÃ­ estÃ¡n las variables que TypeORM realmente usa
      DB_HOST: db # nombre del servicio de postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: marcas_autos_db
      DB_SSL: 'false' # muy importante: el Postgres del compose NO usa SSL

    ports:
      - '3000:3000'

volumes:
  db_data:
